const path = require('path');
const { query, one, execute } = require('../config/db');
const { ensureAdminTables } = require('../services/bootstrapService');
const { hashPassword, verifyPassword, signToken } = require('../services/authService');
const { parseJson } = require('../utils/helpers');
const AppError = require('../utils/appError');
const CONTENT_MODULES = new Set(['home','activity','events','news','gallery','about']);

exports.login=async(req,res)=>{await ensureAdminTables();const {username,password}=req.body;if(!username||!password)throw new AppError(400,'Username and password are required');const user=await one('SELECT * FROM admin_users WHERE username=? LIMIT 1',[username]);if(!user)throw new AppError(401,'Invalid username or password');if(user.status!=='active')throw new AppError(403,'User is blocked. Contact Super Admin to activate this login.');const now=new Date();if(user.locked_until&&new Date(user.locked_until)>now){const mins=Math.max(1,Math.ceil((new Date(user.locked_until)-now)/60000));throw new AppError(423,`Too many wrong attempts. Try again after ${mins} minute(s).`);}if(!verifyPassword(password,user.password_hash||'')){let failed=Number(user.failed_attempts||0)+1;let locks=Number(user.lock_count||0);if(failed>=3){locks+=1;if(locks>=3){await execute("UPDATE admin_users SET failed_attempts=0,lock_count=?,locked_until=NULL,status='inactive' WHERE id=?",[locks,user.id]);throw new AppError(403,'User blocked after repeated failed login. Contact Super Admin.');}const until=new Date(Date.now()+10*60000);await execute('UPDATE admin_users SET failed_attempts=0,lock_count=?,locked_until=? WHERE id=?',[locks,until,user.id]);throw new AppError(423,'Too many wrong attempts. Login locked for 10 minutes.');}await execute('UPDATE admin_users SET failed_attempts=? WHERE id=?',[failed,user.id]);throw new AppError(401,`Invalid username or password. ${3-failed} attempt(s) remaining.`);}await execute('UPDATE admin_users SET failed_attempts=0,locked_until=NULL WHERE id=?',[user.id]);res.json({access_token:signToken(user.username,user.role),token_type:'bearer',user:{id:user.id,name:user.name,username:user.username,role:user.role,status:user.status}});};
exports.dashboard=async(req,res)=>{const [[i],[d],[g],[e],[v],latest]=await Promise.all([query('SELECT COUNT(*) total FROM inquiries'),query('SELECT COUNT(*) total FROM donations'),query('SELECT COUNT(*) total FROM gallery'),query("SELECT COUNT(*) total FROM events WHERE status='upcoming'"),query('SELECT COUNT(*) total FROM hari_bhakto'),query('SELECT id,inquiry_type type,full_name name,message,status,created_at FROM inquiries ORDER BY id DESC LIMIT 6')]);res.json({total_inquiries:i.total,total_donations:d.total,total_gallery_images:g.total,upcoming_events:e.total,total_devotees:v.total,latest_messages:latest,role:req.admin.role});};
exports.upload=(req,res)=>{if(!req.file)throw new AppError(400,'File is required');res.status(201).json({url:`/uploads/media/${req.file.filename}`});};
exports.getSettings=async(_req,res)=>{await ensureAdminTables();res.json(await one('SELECT * FROM settings WHERE id=1')||{});};
exports.saveSettings=async(req,res)=>{const d=req.body;await execute('UPDATE settings SET email1=?,email2=?,email3=?,bank_details=?,upi_id=?,upi_qr=?,donation_categories=? WHERE id=1',[d.email1||null,d.email2||null,d.email3||null,d.bank_details||null,d.upi_id||null,d.upi_qr||null,d.donation_categories||null]);res.json({ok:true});};
exports.savePageContent=async(req,res)=>{const key=String(req.body.page_key||'').trim();if(!key)throw new AppError(422,'Page key is required');await execute('INSERT INTO page_content (page_key,content_data) VALUES (?,?) ON DUPLICATE KEY UPDATE content_data=VALUES(content_data)',[key,JSON.stringify(req.body.content_data||{})]);res.json({ok:true});};
async function listModule(module,admin){await ensureAdminTables();if(CONTENT_MODULES.has(module))return query('SELECT * FROM content_items WHERE module=? ORDER BY sort_order,id DESC',[module]);if(module==='inquiries'){assertAdmin(admin);return query('SELECT id,inquiry_type type,full_name name,email,mobile phone,subject,message,status,created_at FROM inquiries ORDER BY id DESC LIMIT 500');}if(module==='donations'){assertAdmin(admin);const rows=await query('SELECT * FROM donations ORDER BY id DESC LIMIT 500');return rows.map(r=>{const n=parseJson(r.notes,{});return{id:r.id,name:r.donor_name,email:r.email,phone:r.mobile,amount:String(r.amount||''),category:r.seva_type,purpose:r.seva_type,receipt_number:r.receipt_number,payment_method:r.payment_method,message:n.notes||'',receipt_status:r.receipt_issued?'Receipt Sent':'Receipt Pending',status:n.admin_status||'New',created_at:r.created_at};});}if(module==='devotees'){assertAdmin(admin);return query('SELECT id,full_name name,father_husband_name,email,mobile phone,whatsapp,gender,date_of_birth,age,address,city,state,pincode,occupation,satsang_attend,photo_data,remarks message,status,created_at FROM hari_bhakto ORDER BY id DESC LIMIT 500');}if(module==='users'){assertSuper(admin);return query('SELECT id,name,username,role,status,failed_attempts,lock_count,locked_until,created_at FROM admin_users ORDER BY id DESC');}throw new AppError(404,'Module not found');}
function assertAdmin(a){if(!['super_admin','admin'].includes(a?.role))throw new AppError(403,'Access denied');}function assertSuper(a){if(a?.role!=='super_admin')throw new AppError(403,'Super Admin only');}
exports.list=async(req,res)=>res.json(await listModule(req.params.module,req.admin));
exports.create=async(req,res)=>{const m=req.params.module,d=req.body;await ensureAdminTables();if(CONTENT_MODULES.has(m)){const r=await execute('INSERT INTO content_items (module,section,title,short_text,content,image_url,video_url,pdf_url,sort_order,status) VALUES (?,?,?,?,?,?,?,?,?,?)',[m,d.section||null,d.title||null,d.short_text||null,d.content||null,d.image_url||null,d.video_url||null,d.pdf_url||null,d.sort_order||0,d.status||'active']);return res.status(201).json({id:r.insertId,ok:true});}if(m==='users'){assertSuper(req.admin);const r=await execute('INSERT INTO admin_users (name,username,password_hash,role,status) VALUES (?,?,?,?,?)',[d.name,d.username,hashPassword(d.password||'Master@123'),d.role||'editor',d.status||'active']);return res.status(201).json({id:r.insertId,ok:true});}throw new AppError(403,'Create is allowed for CMS and users only');};
exports.update=async(req,res)=>{const m=req.params.module,id=Number(req.params.id),d=req.body;await ensureAdminTables();if(CONTENT_MODULES.has(m)){await execute('UPDATE content_items SET section=?,title=?,short_text=?,content=?,image_url=?,video_url=?,pdf_url=?,sort_order=?,status=? WHERE id=? AND module=?',[d.section||null,d.title||null,d.short_text||null,d.content||null,d.image_url||null,d.video_url||null,d.pdf_url||null,d.sort_order||0,d.status||'active',id,m]);return res.json({ok:true});}if(m==='inquiries'){assertAdmin(req.admin);await execute('UPDATE inquiries SET status=? WHERE id=?',[d.status||'contacted',id]);return res.json({ok:true});}if(m==='donations'){assertAdmin(req.admin);await execute('UPDATE donations SET receipt_issued=? WHERE id=?',[d.receipt_status==='Receipt Sent'?1:0,id]);return res.json({ok:true});}if(m==='devotees'){assertAdmin(req.admin);await execute('UPDATE hari_bhakto SET status=? WHERE id=?',[d.status||'active',id]);return res.json({ok:true});}if(m==='users'){assertSuper(req.admin);if(d.password)await execute('UPDATE admin_users SET name=?,username=?,password_hash=?,role=?,status=? WHERE id=?',[d.name,d.username,hashPassword(d.password),d.role,d.status||'active',id]);else await execute('UPDATE admin_users SET name=?,username=?,role=?,status=? WHERE id=?',[d.name,d.username,d.role,d.status||'active',id]);if((d.status||'active')==='active')await execute('UPDATE admin_users SET failed_attempts=0,lock_count=0,locked_until=NULL WHERE id=?',[id]);return res.json({ok:true});}throw new AppError(404,'Module not found');};
exports.remove=async(req,res)=>{const m=req.params.module,id=Number(req.params.id);if(CONTENT_MODULES.has(m))await execute('DELETE FROM content_items WHERE id=? AND module=?',[id,m]);else if(['inquiries','donations','devotees'].includes(m)){assertAdmin(req.admin);const table={inquiries:'inquiries',donations:'donations',devotees:'hari_bhakto'}[m];await execute(`DELETE FROM ${table} WHERE id=?`,[id]);}else if(m==='users'){assertSuper(req.admin);await execute('DELETE FROM admin_users WHERE id=?',[id]);}else throw new AppError(404,'Module not found');res.json({ok:true});};
function csvCell(v){const s=typeof v==='object'?JSON.stringify(v):String(v??'');return `"${s.replace(/"/g,'""')}"`;}
exports.exportFile=async(req,res)=>{assertAdmin(req.admin);const rows=await listModule(req.params.module,req.admin);const columns=rows[0]?Object.keys(rows[0]):['empty'];const csv=[columns.map(csvCell).join(','),...rows.map(r=>columns.map(c=>csvCell(r[c])).join(','))].join('\r\n');const ext=req.params.fmt==='xlsx'?'csv':'txt';res.setHeader('Content-Type',req.params.fmt==='xlsx'?'text/csv; charset=utf-8':'text/plain; charset=utf-8');res.setHeader('Content-Disposition',`attachment; filename=${req.params.module}.${ext}`);res.send('\uFEFF'+csv);};
exports.listModule=listModule;
